### ISSUE TITLE
Also support GitLab merge requests

### ISSUE THREAD

**Issue by ysb33r** [tomasbjerre/violation-comments-to-github-gradle-plugin#3]
This is a brilliant plugin. I would like to suggest that you split it so that GitLab support can be added as well (or ven BitBucket for the poor souls who still has to use it).

If you can split it into a base plugin which has all of the functionality to gather the information, then further plugins can just add the posting support. In other words split `se.bjurr.violations.violation-comments-to-github-gradle-plugin` into `se.bjurr.violations.violation-comments.base` and `se.bjurr.violations.violation-comments.github`.

Maybe add some notes on what needs to be done to add support for other providers or even use it as a base to post the reports elsewhere than just a pull request. In that way anyone can try to extend your plugin with a PR.

**Comment by tomasbjerre** [comment]
Perhaps you have seen this lib:
https://github.com/tomasbjerre/violation-comments-lib
And this plugin for GitLab:
https://wiki.jenkins.io/display/JENKINS/Violation+Comments+to+GitLab+Plugin

But sure. I can see that a Gradle Gitlab plugin is needed as well!

**Comment by tomasbjerre** [comment]
There is a Gradle plugin for GitLab here now:
https://github.com/tomasbjerre/violation-comments-to-gitlab-gradle-plugin
