### ISSUE TITLE
Capability questions

### ISSUE THREAD

**Issue by stkent** [tomasbjerre/violation-comments-to-github-gradle-plugin#4]
Hi!

A colleague of mine maintains a similar plugin to this (https://github.com/btkelly/gnag), which we've been using on Java and Android projects for a while now. I recently discovered your project and have been evaluating it to see what we can learn :) A few quick questions:

- Am I correct in understanding that your plugin doesn't package third-party checking tools, but instead relies on them being independently applied to the target project?
- Is there any way to generate a local, aggregated report, or are comments GitHub-only?

Thanks, and keep up the good work! 💯

**Comment by tomasbjerre** [comment]
First question, yes.

Second question, no. I think it would be better to create a whole new plugin for aggregating reports. Should be a simple thing using the [Violations Lib](https://github.com/tomasbjerre/violations-lib).

**Comment by stkent** [comment]
Cool, thanks for the info!
