### ISSUE TITLE
Option to fail the build if violations in changeset

### ISSUE THREAD

**Issue by winterDroid** [tomasbjerre/violation-comments-to-github-gradle-plugin#5]
It would be great to be able to configure the plugin in a way to fail the build if x amount of violations are found in the changeset.

**Comment by tomasbjerre** [comment]
I created a new plugin for that purpose:
https://github.com/tomasbjerre/violations-gradle-plugin

**Comment by winterDroid** [comment]
Cool thanks. Downside of using both plugins then is that there are more github requests and parsing happens twice which might take longer.

**Comment by tomasbjerre** [comment]
The nw plugin does not integrate with github.

Den 24 dec. 2017 13:04 skrev "Marc Prengemann" <notifications@github.com>:

**Comment by winterDroid** [comment]
Oh true. Especially just failing when issues in the changeset were found would be beneficial since it would allow to incrementally clean up the code base.

**Comment by tomasbjerre** [comment]
I would probably

* Introduce it in the next release branch (probably develop or master
depending on branch strategy).
* Set maxViolations to the lowest possible value.
* Decrease it as violations are fixed.

Then any pull request that adds violations would fail.

Den 24 dec. 2017 13:18 skrev "Marc Prengemann" <notifications@github.com>:

**Comment by winterDroid** [comment]
Yeah that would work as well but I guess it is too much manual work. I'll stay using my custom fork then 🙂

**Comment by tomasbjerre** [comment]
Do you have that code on GitHub?

I think it could be added here, to introduce the feature in all the plugins:
https://github.com/tomasbjerre/violation-comments-lib/blob/master/src/main/java/se/bjurr/violations/comments/lib/CommentsCreator.java#L47

**Comment by winterDroid** [comment]
No I don't have it on github. But essentially I'm using the CommentCreator to get the amount of comments to be created. If that greater than my max violations definition, it throws a GradleException to fail the build.

**Comment by tomasbjerre** [comment]
I added ability to report only violations in specific changeset. Its released in https://github.com/tomasbjerre/violations-gradle-plugin now.
