### ISSUE TITLE
GITHUB_PULLREQUESTID and $TRAVIS_PULL_REQUEST

### ISSUE THREAD

**Issue by leinardi** [tomasbjerre/violation-comments-to-github-gradle-plugin#6]
I am trying to get this plugin to work in one of my open source project on GitHub but I have issues finding an updated working example (the violations-test is quite outdated and I don't think still works with TravisCI).

The readme suggest to use this for TravisCI:
`./gradlew violationCommentsToGitHub -DGITHUB_PULLREQUESTID=$TRAVIS_PULL_REQUEST -DGITHUB_OAUTH2TOKEN=$GITHUB_OAUTH2TOKEN`

But the $TRAVIS_PULL_REQUEST is just a boolean: https://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/

How can I get the GITHUB_PULLREQUESTID? And what should look like? Just an integer? Or a string like `#12`?

**Comment by tomasbjerre** [comment]
https://docs.travis-ci.com/user/environment-variables/ 

> TRAVIS_PULL_REQUEST The pull request number if the current job is a pull request, “false” if it’s not a pull request.

I think it is just an integer.

**Comment by leinardi** [comment]
But I made a PR to test the plugin and I am getting false as result (ignore the comments, they are made forcing the GITHUB_PULLREQUESTID manually to 19):
PR: https://github.com/leinardi/FloatingActionButtonSpeedDial/pull/19
Build: https://travis-ci.org/leinardi/FloatingActionButtonSpeedDial/builds/363799175#L1586

**Comment by leinardi** [comment]
Oh never mind, the `continuous-integration/travis-ci/pr` has the right number: https://travis-ci.org/leinardi/FloatingActionButtonSpeedDial/builds/363799183#L1594

Sorry for the noise :)
