### ISSUE TITLE
Q: Is there a way to keep old comments which have an ongoing discussion?

### ISSUE THREAD

**Issue by blipinsk** [tomasbjerre/violation-comments-to-github-gradle-plugin#9]
Not an issue, just a question.
With `keepOldComments=false` old comments are removed, regardless of the discussion which might be ongoing in the thread. 
Is it possible to remove only those old comments which were not commented further?

**Comment by tomasbjerre** [comment]
No that feature is not implemented.

Den tors 26 mars 2020 18:10Bartek Lipinski <notifications@github.com> skrev:

**Comment by blipinsk** [comment]
Ok, thanks for responding. Closing.
